[project]
name = "mycloc"
version = "0.1.0"
description = "Count the Lines of blanks, comments, codes in Files or Path"
readme = "README.md"
requires-python = ">=3.13"
authors = [
    {name = "He Zijue", email = "jue1251665735@outlook.com"},
]
dependencies = []
