print("Hello world! ! !")   # 1
print("Hello world! ! !")
print("Hello world! ! !")
print("Hello world! ! !")
print("Hello world! ! !")
print("Hello world! ! !")
print("Hello world! ! !")
print("Hello world! ! !")
print("Hello world! ! !")
print("Hello world! ! !")